//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hostel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reservation()
        {
            this.Earning = new HashSet<Earning>();
        }
    
        public int Id { get; set; }
        public int Guest_id { get; set; }
        public int Beds_id { get; set; }
        public int Guest_Phone { get; set; }
        public System.DateTime Check_in { get; set; }
        public System.DateTime Check_out { get; set; }
        public int Price { get; set; }
    
        public virtual Beds Beds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Earning> Earning { get; set; }
        public virtual Guests Guests { get; set; }
    }
}
